export { default as FailedModal } from './FailedModal'
export { default as CongratesModal } from './CongratesModal'
export { default as ConfirmModal } from './ConfirmModal'
export { default as GuideModal } from './GuideModal'
export { default as ChangeNameModal } from './ChangeUsername'